server:
  port: 8080

spring:
  application:
    name: event-storage-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      # Снижаем linger для минимальной latency produce
      properties:
        linger.ms: 5
        batch.size: 65536

logging:
  level:
    root: INFO
    one.idsstorage: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        write_latency_ms: true
        read_latency_ms: true
        batch_wait_time: true
        batch_flush_latency: true
        batch_size: true

app:
  clickhouse:
    url: ${APP_CLICKHOUSE_URL:http://localhost:8123}
  records:
    batch-size: ${APP_RECORDS_BATCH_SIZE:5000}
  hot-attributes:
    columns:
      - name: attr_lang
        source-key: lang
        ch-type: "LowCardinality(String)"
      - name: attr_source
        source-key: source
        ch-type: "LowCardinality(String)"
      - name: attr_score
        source-key: score
        ch-type: Int32
        expression: "toInt32OrZero(attrs['score'])"
