spring:
  application:
    name: event-storage-service
  
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

server:
  port: 8080

clickhouse:
  url: ${CLICKHOUSE_URL:jdbc:clickhouse://localhost:8123/default}

logging:
  level:
    org.springframework.kafka: INFO
    com.example.eventstorage: DEBUG

